---
- name: Install NFS utils
  yum:
    name: nfs-utils
    state: present

- name: Create NFS export directory
  file:
    path: "{{ nfs_export_path }}"
    state: directory
    owner: nobody
    group: nobody
    mode: '0777'

- name: Configure exports
  lineinfile:
    path: /etc/exports
    line: "{{ nfs_export_path }} *(rw,sync,no_subtree_check,no_root_squash)"
    state: present
  notify: Reload Exports

- name: Start and enable NFS server
  service:
    name: nfs-server
    state: started
    enabled: yes
